"""Fix backref in Question

Revision ID: 42157c44a063
Revises: 5c5601edb67d
Create Date: 2022-04-14 17:45:47.060660

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '42157c44a063'
down_revision = '5c5601edb67d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_mark')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_mark',
    sa.Column('answers_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('questions_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['answers_id'], ['answers.id'], name='question_mark_answers_id_fkey'),
    sa.ForeignKeyConstraint(['questions_id'], ['questions.id'], name='question_mark_questions_id_fkey')
    )
    # ### end Alembic commands ###
