"""Fix Answer primary key

Revision ID: 533ece399576
Revises: 42157c44a063
Create Date: 2022-04-14 23:40:05.791878

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '533ece399576'
down_revision = '42157c44a063'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interviews', 'summary',
               existing_type=sa.VARCHAR(length=512),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interviews', 'summary',
               existing_type=sa.VARCHAR(length=512),
               nullable=True)
    # ### end Alembic commands ###
